name: dev
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip=25.0
  - cudnn=8.9
  - cudatoolkit
  - matplotlib=3.5
  - seaborn=0.13.0
  - scikit-learn=1.6.1
  - box2d-py=2.3
  - einops=0.7.0
  - glew=2.1
  - h5py=3.10
  - numpy=1.26.4
  - pandas=2.2
  - openai=1.5.0
  - wandb=0.16.1
  - tensorboard=2.17
  - swig=4.1
  - moviepy=1.0.3
  - pygame=2.5
  - gym=0.26.1
  - opencv=4.8
  - lockfile=0.12.2
  - jupyter=1.1.1
  - ipython=8.34
  - pip:
    - jax[cuda]
    - flax==0.10.4
    - optax==0.2.4
    - chex==0.1.89
    - torch==2.6.0
    - torchvision==0.21.0
    - torchmetrics==1.6.3
    - -f https://storage.googleapis.com/jax-releases/jax_cuda_releases.html
